[CAS-911] Fix multiline messages
GetStream/stream-chat-android pull request #1748
Opened 2021-04-19 09:35 UTC by bychkovdmitry

https://stream-io.atlassian.net/browse/CAS-911
https://github.com/GetStream/stream-chat-android/issues/1746

### 🎯 Goal

Fix multi-line messages which are shown in single line

### 🛠 Implementation details

Added corresponding plugin to our markdown wrapper

### 🎨 UI Changes

_ Add relevant screenshots_

| Before | After |
| --- | --- |
| ![device-2021-04-19-123216](https://user-images.githubusercontent.com/9600921/115214578-53593700-a10b-11eb-9f50-664dd47405de.png) | ![device-2021-04-19-122941](https://user-images.githubusercontent.com/9600921/115214586-5522fa80-a10b-11eb-9855-ca1eb60b2abd.png) |

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [x] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (CMS, cookbooks, tutorial)
- [x] Reviewers added

### 🎉 GIF

![giphy](https://user-images.githubusercontent.com/9600921/115214943-ae8b2980-a10b-11eb-8bdb-5492cfd66ce6.gif)

2021-04-19 10:07 UTC, samiuelson approved these changes

2021-04-19 10:08 UTC, samiuelson commented
Fixes https://github.com/GetStream/stream-chat-android/issues/1746

2021-04-19 10:17 UTC, JcMinarro requested changes
Could you add this implementation to the old UI as well?

2021-04-20 14:22 UTC, JcMinarro approved these changes

2021-04-20 14:32 UTC, merged