[CAS-1149] Move draft query channels filter to the sample app
GetStream/stream-chat-android pull request #2095
Opened 2021-07-28 19:57 UTC by bychkovdmitry

https://stream-io.atlassian.net/browse/CAS-1149

### 🎯 Goal

Move "draft" query channels filter from SDK to sample app

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))
- [x] Reviewers added

### 🎉 GIF

![giphy (1)](https://user-images.githubusercontent.com/9600921/127387354-54fb0537-8804-44d5-9ada-8206fe6fa624.gif)

2021-07-28 19:58 UTC, bychkovdmitry commented on stream-chat-android-sample/src/main/kotlin/io/getstream/chat/sample/feature/channels/ChannelsFragment.kt
> +    }
Even though we don't create "draft" channels in the old sample app we still share the same environment with the new sample app where such channels are a common occurrence.

2021-07-30 16:15 UTC, leandroBorgesFerreira approved these changes

2021-08-02 07:26 UTC, adasiewiczr requested changes

2021-08-02 07:26 UTC, adasiewiczr commented on stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/ChannelListFragment.kt
> +                Filters.`in`("members", listOf(ChatClient.instance().getCurrentUser()?.id ?: "")),
Setting the user is an async operation and we don't wait until it's finished. There might be a case when this view model is created before the user id set and we'll display wrong channels

2021-08-05 10:43 UTC, adasiewiczr approved these changes
As discussed on Slack - we are going to merge it and tackle this case in a separate task

2021-08-05 11:39 UTC, merged