[CAS-1170] Add support for French
GetStream/stream-chat-android pull request #2143
Opened 2021-08-04 10:49 UTC by adasiewiczr

https://stream-io.atlassian.net/browse/CAS-1170

### 🎯 Goal

Add French translations

### 🛠 Implementation details

Added French translations based on Flutter SDK and Google Translate.
You can find English strings here:
- [Client](https://github.com/GetStream/stream-chat-android/blob/develop/stream-chat-android-client/src/main/res/values/strings.xml)
- [Common](https://github.com/GetStream/stream-chat-android/blob/develop/stream-chat-android-ui-common/src/main/res/values/strings.xml)
- [UI Components](https://github.com/GetStream/stream-chat-android/tree/develop/stream-chat-android-ui-components/src/main/res/values)

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))
- [x] Reviewers added

2021-08-04 10:51 UTC, adasiewiczr commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_common.xml
> +    <string name="stream_ui_user_status_last_seen_just_now">Last seen just now</string>
I have no idea how to translate this one

2021-08-04 14:42 UTC, sachaarbonel requested changes
Added some reviews

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_mute_user">Utilisateur muter</string>
```suggestion
    <string name="stream_ui_message_list_mute_user">Mettre en sourdine l\'utilisateur</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_unmute_user">Utilisateur unmute</string>
```suggestion
    <string name="stream_ui_message_list_unmute_user">Désactiver la mise en sourdine de l\'utilisateur</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_block_user">Bloquer un utilisateur</string>
```suggestion
    <string name="stream_ui_message_list_block_user">Bloquer l\'utilisateur</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_delete_confirmation_message">Voulez-vous vraiment supprimer définitivement ce message ?</string>
```suggestion
    <string name="stream_ui_message_list_delete_confirmation_message">Êtes-vous sûr de vouloir supprimer définitivement ce message ?</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_attachment_invalid_mime_type">Quelque chose s\'est mal passé. Impossible d\'ouvrir la pièce jointe: %s</string>
```suggestion
    <string name="stream_ui_message_list_attachment_invalid_mime_type">Un problème est survenu. Impossible d\'ouvrir la pièce jointe: %s</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_error_mute_user">Échec à l\'utilisateur muet</string>
```suggestion
    <string name="stream_ui_message_list_error_mute_user">Échec de la mise en sourdine de l\'utilisateur</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_empty">Aucune canaux disponible</string>
```suggestion
    <string name="stream_ui_channel_list_empty">Aucun canal disponible</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_you">Toi</string>
```suggestion
    <string name="stream_ui_channel_list_you">Vous</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_untitled_channel">Le canal sans nom</string>
```suggestion
    <string name="stream_ui_channel_list_untitled_channel">Canal sans nom</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_leave_channel">Quitter le Group</string>
```suggestion
    <string name="stream_ui_channel_list_leave_channel">Quitter le Groupe</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_error_hide_channel">Échec de la masquer la canal</string>
```suggestion
    <string name="stream_ui_channel_list_error_hide_channel">Echec du masquage du canal</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_error_delete_channel">Échec de la suppression de la canal</string>
```suggestion
    <string name="stream_ui_channel_list_error_delete_channel">Échec de la suppression du canal</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_error_leave_channel">Échec de la sortie de la canal</string>
```suggestion
    <string name="stream_ui_channel_list_error_leave_channel">Échec de sortie du canal</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_channel_list.xml
> +    <string name="stream_ui_channel_list_delete_confirmation_message">Êtes-vous sûr de vouloir supprimer définitivement ce\nmessage?</string>
```suggestion
    <string name="stream_ui_channel_list_delete_confirmation_message">Êtes-vous sûr de vouloir supprimer définitivement cette conversation?</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
> +    <string name="stream_ui_message_input_permission_setting_message">Activer les autorisations sur Paramètres de l\'application</string>
```suggestion
    <string name="stream_ui_message_input_permission_setting_message">Activez les autorisations dans les paramètres de l\'application</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
> +    <string name="stream_ui_message_input_permission_storage_message">Des autorisations d\'accès au stockage sont nécessaires pour pouvoir envoyer et enregistrer des photos, des vidéos, de la musique
```suggestion
    <string name="stream_ui_message_input_permission_storage_message">Des autorisations d\'accès au stockage sont nécessaires pour pouvoir envoyer et sauvegarder des photos, des vidéos, de la musique et d\'autres fichiers.</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
> +    <string name="stream_ui_message_input_permission_camera_title">Caméra et stockage Autorisation d\'accès</string>
```suggestion
    <string name="stream_ui_message_input_permission_camera_title">Permission d\'accès aux caméras et au stockage</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
> +    <string name="stream_ui_message_input_capture_media">Capture d\'image ou vidéo</string>
```suggestion
    <string name="stream_ui_message_input_capture_media">Capture d\'image ou de vidéo</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-client/src/main/res/values-fr/strings.xml
> +    <string name="stream_chat_notification_reply">Réponse</string>
```suggestion
    <string name="stream_chat_notification_reply">Répondre</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-client/src/main/res/values-fr/strings.xml
> +    <string name="stream_chat_notification_type_hint">Tapez le message</string>
```suggestion
    <string name="stream_chat_notification_type_hint">Tapez votre message</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
> +    <string name="stream_ui_message_input_capture_media">Capture d\'image ou vidéo</string>
```suggestion
    <string name="stream_ui_message_input_capture_media">Capture d\'image ou de vidéo</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-common/src/main/res/values-fr/strings.xml
> +    <string name="stream_ui_message_list_attachment_invalid_mime_type">Quelque chose s\'est mal passé. Impossible d\'ouvrir la pièce jointe: %s</string>
```suggestion
    <string name="stream_ui_message_list_attachment_invalid_mime_type">Un problème est survenu. Impossible d\'ouvrir la pièce jointe: %s</string>
```

2021-08-04 14:42 UTC, sachaarbonel commented on stream-chat-android-ui-components/src/main/res/values-fr/strings_message_list.xml
> +    <string name="stream_ui_message_list_attachment_upload_complete">Téléchargement terminé, traitement…</string>
```suggestion
    <string name="stream_ui_message_list_attachment_upload_complete">Transfert terminé, traitement…</string>
```

2021-08-04 15:21 UTC, JcMinarro commented
Thanks @sachaarbonel for the review

2021-08-06 09:20 UTC, JcMinarro approved these changes

2021-08-06 09:20 UTC, merged