[CAS-895] Korean translation
GetStream/stream-chat-android pull request #2202
Opened 2021-08-11 15:04 UTC by bychkovdmitry

### 🎯 Goal

Korean translations for the following strings:

```xml
<string name="stream_ui_message_list_pinned_message">Pinned by %s</string>
<string name="stream_ui_message_list_pinned_message_you">You</string>
<string name="stream_ui_message_list_pin_message">Pin to Conversation</string>
<string name="stream_ui_message_list_unpin_message">Unpin from Conversation</string>
<string name="stream_ui_message_list_error_pin_message">Failed to pin message</string>
<string name="stream_ui_message_list_error_unpin_message">Failed to unpin message</string>
<string name="stream_ui_pinned_message_list_empty_title">No pinned messages</string>
<string name="stream_ui_pinned_message_list_empty_description"><![CDATA[Long-press an important message and choose <b>Pin to conversation</b>]]></string>
<string name="stream_ui_pinned_message_list_results_error">An error occurred</string>
```

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))
- [x] Reviewers added

2021-08-11 16:29 UTC, EricSSartorius requested changes
Update korean translations

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
> +    <string name="stream_ui_message_list_pinned_message_you">너</string>
당신

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
> +    <string name="stream_ui_message_list_pinned_message">%s에 의해 고정됨</string>
%s의 핀

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
> +    <string name="stream_ui_message_list_pin_message">대화에 고정</string>
대화에 핀하기

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
> +    <string name="stream_ui_message_list_unpin_message">대화에서 고정 해제</string>
대화에서 핀 해제

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
> +    <string name="stream_ui_message_list_error_pin_message">메시지를 고정하지 못했습니다.</string>
메시지를 핀하지 못했습니다

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
> +    <string name="stream_ui_message_list_error_unpin_message">메시지를 고정 해제하지 못했습니다.</string>
메시지를 핀 해제하지 못했습니다

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_pinned_message_list.xml
> +    <string name="stream_ui_pinned_message_list_empty_title">고정된 메시지 없음</string>
핀된 메시지 없음

2021-08-11 16:29 UTC, EricSSartorius commented on stream-chat-android-ui-components/src/main/res/values-ko/strings_pinned_message_list.xml
> +    <string name="stream_ui_pinned_message_list_empty_description"><![CDATA[중요한 메시지를 길게 누르고 <b>대화에 고정</b>을 선택합니다.]]></string>
<string name="stream_ui_pinned_message_list_empty_description"><![CDATA[중요한 메시지를 길게 누르고 <b>대화에 핀하기</b>을 선택합니다.]]></string>

2021-08-12 08:18 UTC, adasiewiczr approved these changes

2021-08-12 09:35 UTC, merged