[CAS-1421] Docs for avatar customization
GetStream/stream-chat-android pull request #2760
Opened 2021-12-10 13:49 UTC by leandroBorgesFerreira

### 🎯 Goal

Document how to configure avatar

### 🧪 Testing

run: `npx stream-chat-docusaurus -i -s`. In the root folder and read the documentation

### ☑️Contributor Checklist

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [ ] Thread with the PR link started in a respective Slack channel (#android-team or #compose-chat-sdk-team) (required)
- [x] PR targets the `develop` branch

#### Code & documentation
- ~[ ] Changelog is updated with client-facing changes~
- ~[ ] New code is covered by unit tests~
- ~[ ] Comparison screenshots added for visual changes~
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

_Please provide a suitable gif that describes your work on this pull request_

2021-12-12 23:12 UTC, skydoves approved these changes
Looks good to me. 👍

2021-12-12 23:12 UTC, skydoves commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +**If you only would like  to change the gradient colors for the avatar**, you can use `stream_ui_avatar_gradient_colors`. You can override this color in your color xml file like:
```suggestion
**If you only would like to change the gradient colors for the avatar**, you can use `stream_ui_avatar_gradient_colors`. You can override this color in your color xml file like: 
```

2021-12-13 09:22 UTC, samiuelson approved these changes

2021-12-13 09:47 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +You can configure avatar shape, border width, online indicator and other aspects using [AvatarStyle](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android/src/main/java/com/g
```suggestion
You can configure avatar shape, border width, online indicator and other aspects using [AvatarStyle](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android/src/main/java/com/getstream/sdk/chat/view/messages/AvatarStyle.kt). You can create this kind of avatar by changing the shape and border-radius: 
```

2021-12-13 09:47 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +It is also possible to change the background and the picture using `AvatarBitmapFactory`.
```suggestion
You can also change the background and the picture using `AvatarBitmapFactory`.
```

2021-12-13 09:47 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +**If you don't want to use avatars from internet and only use the default avatar**, you can call `createDefaultUserBitmap` inside `createUserBitmap` in your custom implementation of `AvatarBitmapFact
```suggestion
**If you don't want to use avatars from the internet and only use the default avatar**, you can call `createDefaultUserBitmap` inside `createUserBitmap` in your custom implementation of `AvatarBitmapFactory`
```

2021-12-13 10:02 UTC, adasiewiczr requested changes

2021-12-13 10:02 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +**If you only would like  to change the gradient colors for the avatar**, you can use `stream_ui_avatar_gradient_colors`. You can override this color in your color xml file like:
```suggestion
**If you only would like to change the gradient colors for the default avatar**, you can use `stream_ui_avatar_gradient_colors`. You can override this color in your color xml file like: 
```

2021-12-14 10:53 UTC, adasiewiczr reviewed
Looks great overall. Added small suggestions

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +The SDK uses `AvatarView` in the lists of channels, users and in the message lists. The avatar is a small picture that identifies an specific channel or user.
```suggestion
The `AvatarView` is used in the lists of channels, users, and messages. The avatar is a small picture that identifies a specific channel or user. 
```

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +For `Channel`, it is used the property Channel.image and for User, it is used `User.image`. The image in the AvatarView, will be the image's url in those fields:
```suggestion
The image in the `AvatarView` is being displayed based on `image` property, present in both `Channel` and `User` objects:
```

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +If there's no url to be displayed, the SDK falls back to a gradient color with initials for the channel or user:
```suggestion
The `AvatarView` will use default gradient color with initials if the `image` property cannot be loaded:
```

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +**If you don't want to use avatars from the internet and only use the default avatar**, you can call `createDefaultUserBitmap` inside `createUserBitmap` in your custom implementation of `AvatarBitmap
```suggestion
**If you don't want to use avatars from the internet and only use the default avatar**, you can call `createDefaultUserBitmap` inside `createUserBitmap` in your custom implementation of `AvatarBitmapFactory`:
```

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +This way use default avatar with gradient colors and initials for the users.
I think we don't need it. You already described it above the snippet
```suggestion
```

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +The normal color set include a variaty of colors:
```suggestion
The default color set includes a variety of colors: 
```

2021-12-14 10:53 UTC, adasiewiczr commented on docusaurus/docs/Android/03-ui/03-chatui.mdx
> +You can override this color in your color xml file. And expand of reduce the number of supported color, like the example
```suggestion
The set can be overridden in the `color.xml` file - you can expand or reduce the number of supported colors, like in the example below:
```

2021-12-14 14:48 UTC, adasiewiczr approved these changes

2021-12-14 15:27 UTC, merged