[CAS-1274] Substitute ChatDomain::createChannel
GetStream/stream-chat-android pull request #2854
Opened 2021-12-30 17:03 UTC by ogkuzmin

### 🎯 Goal

Subtitute usage of `ChatDomain::createChannel`

### 🛠 Implementation details

1. New extension `ChatClient::createChannel(channle: Channel)`
2. New `CreateChannelService` that encapsulates logic of creating channel

### 🧪 Testing

Run old UI sample and create channel and be sure nothing has changed.

### ☑️Contributor Checklist

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [ ] Thread with the PR link started in a respective Slack channel (#android-team or #compose-chat-sdk-team) (required)
- [x] PR targets the `develop` branch

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- <del> [ ] New code is covered by unit tests </del>
- <del> [ ] Comparison screenshots added for visual changes </del>
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

<img src="https://media3.giphy.com/media/l2Jea20ZW8lxsBSik/giphy.gif"/>

2022-01-06 08:16 UTC, amitkma commented on stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
> +    return domainImpl()
This is incorrect. It causes StackOverFlow exception due to recursion.

2022-01-06 08:17 UTC, amitkma requested changes
Review in progress.

2022-01-06 08:17 UTC, amitkma commented on stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
> +    return domainImpl()
This is incorrect. It causes StackOverFlow exception due to recursion.

2022-01-13 09:46 UTC, adasiewiczr reviewed
@amitkma can you take a look on tests?

2022-01-13 09:46 UTC, adasiewiczr commented on DEPRECATIONS.md
> +| `ChatDomain.createChannel` | 2022.01.04<br/>4.26.0 |  2022.01.18<br/>⌛ | 2022.02.01 ⌛ | Use extension function `ChatClient.createChannel` instead |
```suggestion
| `ChatDomain.createChannel` | 2022.01.21<br/>4.27.0 |  2022.02.04<br/>⌛ | 2022.02.12 ⌛ | Use extension function `ChatClient.createChannel` instead |
```

2022-01-13 09:46 UTC, adasiewiczr commented on stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
> +        message = "createChannel is deprecated. Use extension function ChatClient::createChannel instead",
```suggestion
        message = "createChannel is deprecated. Use ChatClient::createChannel extension function instead",
```

2022-01-13 09:46 UTC, adasiewiczr commented on stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt
> +        message = "createChannel is deprecated. Use extension function ChatClient::createChannel instead",
```suggestion
        message = "createChannel is deprecated. Use ChatClient::createChannel extension function  instead",
```

2022-01-13 13:36 UTC, amitkma commented
I started to look into tests. Will update PR today.

2022-01-13 17:50 UTC, amitkma submitted a review, later dismissed

2022-01-13 17:51 UTC, amitkma reviewed
Looks good to me. @adasiewiczr could you please review?

2022-01-14 07:41 UTC, adasiewiczr approved these changes
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [x] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs

2022-01-14 07:41 UTC, merged