[3142] Improve Compose code structure
GetStream/stream-chat-android pull request #3143
Opened 2022-02-25 19:25 UTC by bychkovdmitry

### 🎯 Goal

_Describe why we are making this change_

### 🛠 Implementation details

Renamed the "/state/channel/" package to "/state/channels/" for consistency.

/state/channel/list/ChannelAction.kt               -> /state/channels/list/ChannelAction.kt
/state/channel/list/ChannelItemState.kt         -> /state/channels/list/ChannelItemState.kt
/state/channel/list/ChannelOptionState.kt     -> /state/channels/list/ChannelOptionState.kt
/state/channel/list/ChannelsState.kt               -> /state/channels/list/ChannelsState.kt

Renamed the "/viewmodel/channel" package to "/viewmodel/channels/" for consistency.

/viewmodel/channel/ChannelListViewModel.kt              -> /viewmodel/channels/ChannelListViewModel.kt
/viewmodel/channel/ChannelViewModelFactory.kt       -> /viewmodel/channels/ChannelViewModelFactory.kt

Moved the contents of "/ui/imagepreview/", "/ui/mediapreview/" and "/ui/filepreview/" to "/ui/attachments/preview/".

/ui/imagepreview/ImagePreviewActivity.kt            -> /ui/attachments/preview/ImagePreviewActivity.kt
/ui/imagepreview/ImagePreviewContract.kt         -> /ui/attachments/preview/ImagePreviewContract.kt
/ui/mediapreview/MediaPreviewActivity.kt            -> /ui/attachments/preview/MediaPreviewActivity.kt
/ui/filepreview/AttachmentPreviewHandler.kt       -> /ui/attachments/preview/handler/AttachmentPreviewHandler.kt
/ui/filepreview/DocumentAttachmentPreviewHandler.kt -> /ui/attachments/preview/handler/DocumentAttachmentPreviewHandler.kt
/ui/filepreview/MediaAttachmentPreviewHandler.kt    -> /ui/attachments/preview/handler/MediaAttachmentPreviewHandler.kt
/ui/filepreview/UrlAttachmentPreviewHandler.kt         -> /ui/attachments/preview/handler/UrlAttachmentPreviewHandler.kt

### ☑️Contributor Checklist

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

2022-03-04 15:35 UTC, adasiewiczr requested changes
I'm not sure if using plural nouns is the right direction as:
1. Singular is more appropriate in some cases - for example `channels.list`. For me `channel.list` sounds better and should be the preferred name
2. Take a look at ui-components structure - we are using singular everywhere and maybe it would be a good idea to unify it

Would love to get more opinions on that! I'll request changes just to be sure we don't merge it before discussion/getting extra reviews.

2022-03-07 07:36 UTC, filbabic commented
@adasiewiczr @MarinTolic @bychkovdmitry So the reason why I like plural more is because to me it makes more sense to say that it's a "feature that shows channels` rather than a "feature that shows channel items". Similarly, I would much rather say "Channels screen" or "the Channels feature" than "Channel screen" or "Channel feature".

Because singular implies there is only one. Which is why we had to come up with things like "ChannelListScreen/Activity" as we didn't use "ChannelsScreen/Activity".

Similarly, for Messages, I don't think it's a "MessageScreen/MessageActivity", it's "Messages", given that there can be many.

In UI Components we use singular, but for Compose it felt natural to go with the plural 🤷 

There is one example here also: 
![image](https://user-images.githubusercontent.com/17215808/156986919-5ebc8c1f-090b-49b5-a07e-9dbd5e0f521e.png)

Where we have packages like "actions" or "extensions". Because we know there are more of them and they refer to more than 1 item in the scope of the package/functionality and even though we know that for our Components too (they're related to "messages" not "_a_ message") not sure why we went for another type of naming. 

Now - either way, it's a pretty large breaking change. I feel like the best would be to have it universal obviously (for consistency), but packages only matter for imports of our clients, so I propose we just keep the structure per-UI SDK as we feel it makes sense?

E.g. singular for XML and plural for Compose? WDYT

2022-03-07 10:23 UTC, filbabic commented
### ☑️Reviewer Checklist
- [x] Compose sample runs & works
- [x] Release notes and docs clearly describe changes

Nicely done - check my comment above for why I think this is okay even if it's plural and deviates from other naming (e.g. XML).

2022-03-07 10:30 UTC, adasiewiczr approved these changes

2022-03-07 12:31 UTC, merged