Feature/3361 allow ignore mutes for unread count
GetStream/stream-chat-android pull request #3363
Opened 2022-04-20 08:59 UTC by filbabic

### 🎯 Goal
Some of our customers want to support social media like use cases where muted channels receive unread count events.

This is required to support it. Fixes #3361 

### 🛠 Implementation details

Added a flag in the OP `Config` that affects the unread count logic.

### 🧪 Testing

1. Run the app on two devices on this branch with the applied patch.
2. Log in to two different users who are in the same channel.
3. Mute a channel with one user and send a message with another. The unread count should update.
4. You can also test by putting the flag to false (default behavior) that the unread count doesn't update when the channel is muted.

<details>
  <summary>Patch file to apply these changes for testing</summary>

```
Index: stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt b/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
--- a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt	(revision 60665b59092afdb9b5238a1c7c7fe90401a0edae)
+++ b/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt	(date 1650444246174)
@@ -67,7 +67,7 @@
             config = Config(
                 userPresence = true,
                 persistenceEnabled = true,
-                ignoreMutesForUnreadCount = false
+                ignoreMutesForUnreadCount = true
             ),
             appContext = context
         )
Index: stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt b/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
--- a/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt	(revision 60665b59092afdb9b5238a1c7c7fe90401a0edae)
+++ b/stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt	(date 1650440259516)
@@ -58,7 +58,7 @@
             config = Config(
                 userPresence = true,
                 persistenceEnabled = true,
-                ignoreMutesForUnreadCount = false
+                ignoreMutesForUnreadCount = true
             ),
             appContext = context
         )

```

</details>

### ☑️Contributor Checklist

#### General
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

2022-04-21 07:54 UTC, adasiewiczr commented on stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/configuration/Config.kt
> +    public val ignoreMutesForUnreadCount: Boolean = false
What do you think about marking it with `@ExperimentalStreamChatAPI`?
The flag should be replaced by the config field at some point

2022-04-21 07:54 UTC, adasiewiczr commented on stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
> +    private val ignoreMutesForUnreadCount: Boolean = false
Do we need this default value here?

2022-04-21 12:22 UTC, adasiewiczr requested changes
The flag is going to be included in Channel's `Config`. Let's wait until feature is implemented on the BE

2022-06-29 10:17 UTC, filbabic commented
Blocked by BE, closing to revisit once it's ready

2022-06-29 10:17 UTC, closed without merging