[3529 && ]
GetStream/stream-chat-android pull request #3772
Opened 2022-06-27 15:13 UTC by MarinTolic

### 🎯 Goal

closes #3529
closes #3770 

### 🛠 Implementation details

#3529

Extracted marking as read into a separate function that triggers a lambda when a new item is visible. 

The benefit of this is that only the newly visible item will call mark as read, where as previously any recomposed item would call mark as read.

#3770

Compare the IDs of the messages that are marked as read, marking the channel as read only when the last item is reached.

### 🧪 Testing

#3529 

Unfortunately testing this one is a little bit convoluted.

### ☑️Contributor Checklist

#### General
- [x] Assigned a person / code owner group (required)
- [ ] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

![catread](https://user-images.githubusercontent.com/37080097/175974150-f738f8b8-22df-4e58-bc6f-e26972b733e5.gif)

2022-06-27 20:38 UTC, MarinTolic commented on stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
> -        chatClient.loadMessageById(cid, message.id, DefaultMessageLimit, DefaultMessageLimit).enqueue()
This was newly deprecated.
It should be replaced in XML too but I didn't want to litter this PR.

2022-06-27 20:42 UTC, MarinTolic commented on stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt
> +    OnLastVisibleItemChanged(lazyListState) { messageIndex ->
One possible consequence I can think of here is having an out of bounds error but brief torture tests did not manage to cause it.

If you can think of a scenario, please test it.

2022-06-28 11:47 UTC, bychkovdmitry approved these changes
LGTM

2022-06-28 11:52 UTC, bychkovdmitry requested changes
Unread count badge is now broken

2022-06-28 12:03 UTC, bychkovdmitry approved these changes

2022-06-29 10:34 UTC, merged