Using Repositories implementations instead of facade
GetStream/stream-chat-android pull request #4126
Opened 2022-09-01 19:40 UTC by leandroBorgesFerreira

### 🎯 Goal

_Describe why we are making this change_

### 🛠 Implementation details

_Describe the implementation_

### 🎨 UI Changes

_Add relevant screenshots_

| Before | After |
| --- | --- |
| img | img |

_Add relevant videos_

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="" controls="controls" muted="muted" />
</td>
<td>
<video src="" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

### 🧪 Testing

_Explain how this change can be tested (or why it can't be tested)_

_Provide a patch below if it is necessary for testing_

<details>

<summary>Provide the patch summary here</summary>

```
Provide the patch code here
```

</details>

### ☑️Contributor Checklist

#### General
- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Assigned a person / code owner group (required)
- [ ] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [ ] PR targets the `develop` branch
- [ ] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

_Please provide a suitable gif that describes your work on this pull request_

2022-09-02 03:58 UTC, skydoves approved these changes
Looks good to me!

2022-09-02 03:58 UTC, skydoves commented on stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
> +            repositoryFacade.observeLatestUsers()
It would be better if we could define the argument names explicitly here.

2022-09-02 07:47 UTC, JcMinarro requested changes
The `RepositoryFacade` was created because when we insert some entities like `channel` (eg: `ChannelRepository::insertChannel`), this entity contains other entities that need to be inserted in a different repository, like for example `user` (eg: `UserReposotory::insertUsers`).
If we use the repositories injected into our `RepositoryFacade` instead of the facade itself, we lose this logic, and it needs to be duplicated every time we use those methods.

Our `RepositoryFacade` implements all our Repository Interfaces, so when a class asks for a concrete repository and we use the `RepositoryFacade`, the class will only be able to access the methods of the concrete repository, and not the rest of our `RepositoryFacade`. There is no issue to use our `RepositoryFacade` there.

2022-09-02 13:06 UTC, leandroBorgesFerreira commented
Hi @JcMinarro. 

One problem that we have with the facade is that we use some overrides in the original implementations that cause duplication when using the interfaces. For example: 
```
userRepository.insertUsers(messageToBeDeleted.users())
messageRepository.insertMessage(messageToBeDeleted, true)
```

This code would call insert user twice because of the implementation of insertMessage of RepositoryFacade: 
```
override suspend fun insertMessage(message: Message, cache: Boolean) {
        insertUsers(message.users())
        messageRepository.insertMessage(message, cache)
}
```

Using `RepositoryFacade` brings this problem with it. Another solution, instead of using the implementations inside the facade would be to erase this method and make sure the other classes are not having this problem (pehaps clean all override), but it is a bigger change. 

What do you think?

2022-09-02 14:41 UTC, JcMinarro commented
> Hi @JcMinarro.
> 
> One problem that we have with the facade is that we use some overrides in the original implementations that cause duplication when using the interfaces. For example:
> 
> ```
> userRepository.insertUsers(messageToBeDeleted.users())
> messageRepository.insertMessage(messageToBeDeleted, true)
> ```
> 
> This code would call insert user twice because of the implementation of insertMessage of RepositoryFacade:
> 
> ```
> override suspend fun insertMessage(message: Message, cache: Boolean) {
>         insertUsers(message.users())
>         messageRepository.insertMessage(message, cache)
> }
> ```
> 
> Using `RepositoryFacade` brings this problem with it. Another solution, instead of using the implementations inside the facade would be to erase this method and make sure the other classes are not having this problem (pehaps clean all override), but it is a bigger change.
> 
> What do you think?

Just that is the case.
Whenever a channel/message is added, we need to add all related users with this entity.
If we forgot to insert them in some place, our SDK could crash when the entity is recovered (And indeed, it was crashing in the past until we implemented the facade and handled this case)

If someone inserts twice the same user, it doesn't create a duplicate.
The code you posted is totally fine.

2022-09-07 06:06 UTC, kanat commented
Hey @JcMinarro 👋

The main issue is that we're doing unnecessary `IO` operations, at least 2 times more than it actually requires 🤷‍♂️
So I suppose by `duplicate` @leandroBorgesFerreira meant not the entities but `IO` operations.

2022-09-07 06:07 UTC, kanat approved these changes
LGTM

2022-09-14 08:34 UTC, JcMinarro commented
> Hey @JcMinarro wave
> 
> The main issue is that we're doing unnecessary `IO` operations, at least 2 times more than it actually requires man_shrugging So I suppose by `duplicate` @leandroBorgesFerreira meant not the entities but `IO` operations.

Those unnecessary `IO` operations can be avoided by removing the `insertUsers()` call from outside of the `repositoryFacade` invocation, because they are not needed.
But we can't allow other users to insert corrupt data to our DB

2022-12-01 14:26 UTC, closed without merging