[4297] V5 Make attachment equality comparisons based on shortened links
GetStream/stream-chat-android pull request #4349
Opened 2022-11-04 18:56 UTC by MarinTolic

### 🎯 Goal

_Describe why we are making this change_

### 🛠 Implementation details

_Describe the implementation_

### 🎨 UI Changes

_Add relevant screenshots_

| Before | After |
| --- | --- |
| img | img |

_Add relevant videos_

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="" controls="controls" muted="muted" />
</td>
<td>
<video src="" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

### 🧪 Testing

_Explain how this change can be tested (or why it can't be tested)_

_Provide a patch below if it is necessary for testing_

<details>

<summary>Provide the patch summary here</summary>

```
Provide the patch code here
```

</details>

### ☑️Contributor Checklist

#### General
- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Assigned a person / code owner group (required)
- [ ] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [ ] PR targets the `develop` branch
- [ ] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

_Please provide a suitable gif that describes your work on this pull request_

2022-11-04 19:05 UTC, MarinTolic commented on stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
> +                                    attachment.assetUrl?.substringBefore("?") ==
substringBefore() will return the original string if it cannot satisfy this condition.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/substring-before.html

2022-11-04 19:05 UTC, MarinTolic commented on stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
> +                            chatClient.deleteMessage(messageId = event.messageId).enqueue(
Because we previously did not do this, we would leave behind an empty message if the last attachment was deleted.

2022-11-10 09:06 UTC, TGazica requested changes
Same as in the V6 pr: https://github.com/GetStream/stream-chat-android/pull/4348#pullrequestreview-1175319581

2022-11-10 12:49 UTC, TGazica approved these changes
Looks good, bug to be fixed in other pr

2022-11-10 13:01 UTC, merged