[4408] Update channel list docs
GetStream/stream-chat-android pull request #4463
Opened 2022-11-21 03:46 UTC by bychkovdmitry

### 🎯 Goal

Closes https://github.com/GetStream/stream-chat-android/issues/4408

Update channel list docs.

### 🎨 UI Changes

### 🧪 Testing

Launch docusaurus with `npx stream-chat-docusaurus -i -s`, and ensure that the changes look good.

### ☑️Contributor Checklist

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

2022-11-28 14:53 UTC, MarinTolic requested changes
Requesting changes due to the agreement that we should not cut the channel list from the screens but rather frame it.

Also, I couldn't get the shimmer/ loading state tutorial to work in a standalone app, but might be a mistake on my end.

2022-11-29 10:16 UTC, bychkovdmitry commented on docusaurus/docs/Android/03-ui/03-channel-components/02-channel-list.mdx
> +* Change the read indicator icon
I'll leave it as is, as mutating a drawable is too complex for this example

2022-11-30 10:58 UTC, MarinTolic approved these changes

2022-11-30 10:58 UTC, MarinTolic commented on docusaurus/docs/Android/03-ui/03-channel-components/02-channel-list.mdx
> +We recommend fetching data from Stream's API using `ChanneListViewModel`, and then rendering it inside `ChannelListView.`
```suggestion
We recommend fetching data from Stream's API using `ChanneListViewModel`, and then rendering it inside `ChannelListView`.
```

2022-11-30 10:58 UTC, MarinTolic commented on docusaurus/docs/Android/03-ui/03-channel-components/02-channel-list.mdx
> +All the logic of subscribing to data emitted by the ViewModel is provided by the bindView function. Other than channel data loading, the ViewModel also handles actions like deleting a channel and lea
```suggestion
All the logic of subscribing to data emitted by the ViewModel is provided by the `bindView` function. Other than channel data loading, the ViewModel also handles actions like deleting a channel and leaving a group conversation by default.
```

2022-11-30 11:23 UTC, merged