[AND-16] Add support for custom membership data
GetStream/stream-chat-android pull request #5502
Opened 2024-12-03 16:02 UTC by VelikovPetar

### 🎯 Goal
Add support for providing custom extra data for members on channel creation and when adding new members to a channel.
Linear: https://linear.app/stream/issue/AND-16/custom-membership-data

### 🛠 Implementation details

#### General changes
- Implement new domain model `MemberData` which holds the mandatory `member(user)Id` and an optional `extraData: Map<String, Any>` for any custom key-value pairs for the member
- Implement corresponding `UpstreamMemberDataDto` and `UpstreamMemberDataDtoAdapter` for handling the `extraData` serialization 

#### `addMembers` changes
- Change `AddMembersRequest` to take `List<UpstreamMemberDataDto>` instead of `List<String>` for the `add_members` field.
- Change `ChatApi.addMembers` method to take `List<MemberData>` instead of `List<String>`
- Implement new `AddMembersRequest` model and expose new `ChatClient/ChannelClient` `addMembers` methods, which take this model as input - which allows passing custom `extraData` for each member. (the existing `addMembers` methods will now use the new ones in the background)
- Add extra data validation for `addMembers` in `ExtraDataValidator`

#### `createChannel` changes
- Implement new `CreateChannelRequest` model which holds `List<MemberData>`(members for the channel) and `Map<String, Any>` (custom data for the channel)
- Expose new `createChannel` methods from `ChatClient`/`ChannelClient` which take the new `CreateChannelRequest` as input (the old methods will now use the new ones in the background)
- Add new `onCreateChannelRequest` method in the `CreateChannelListener` which takes `CreateChannelRequest` as input parameter, and deprecate(⚠️) the old one which takes `List<String>`
- Adapt the `CreateChannelListenerDatabase` to also persist the the new custom data for the members

2024-12-09 13:05 UTC, JcMinarro requested changes

2024-12-09 13:05 UTC, JcMinarro commented on stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
> +    public fun create(request: CreateChannelRequest): Call<Channel> {
Same here.
Request object shouldn't be exposed here

2024-12-09 13:05 UTC, JcMinarro commented on stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
> +    public fun addMembers(request: AddMembersRequest): Call<Channel> {
Same here.
Request object shouldn't be exposed here

2024-12-09 13:05 UTC, JcMinarro commented on stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/Plugin.kt
> +        request: CreateChannelRequest,
Same here

2024-12-09 13:05 UTC, JcMinarro commented on stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/listeners/CreateChannelListener.kt
> +        request: CreateChannelRequest,
Same here

2024-12-10 15:32 UTC, VelikovPetar commented on stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/AddMembersRequest.kt
> +public data class AddMembersRequest(
The new `AddMembersRequest` and `CreateChannelRequest` were not really API objects as they weren't used by the internal api implementation, but they were wrongly placed in the `client/api` package. They are now moved alongside the other public models in the `io.getstream.chat.android.models` package. (commit: 7300d12b3a9afd1d8d5d02dbd5bd55dce6e720d3)
I wasn't sure about their naming, perhaps them having the suffix `-Request` is confusing. Should we maybe rename them to something like `AddMembersData / CreateChannelData` or something similar?

2024-12-13 09:35 UTC, JcMinarro commented on stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/AddMembersRequest.kt
> +public data class AddMembersRequest(
Would be good to remove `-Request` suffix to avoid confusion

2024-12-13 12:09 UTC, JcMinarro approved these changes

2024-12-13 12:09 UTC, merged